// <auto-generated />
namespace HotelRestApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_propertie_to_Guest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_propertie_to_Guest));
        
        string IMigrationMetadata.Id
        {
            get { return "202002091211554_added_propertie_to_Guest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
